config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  devise_for :users, controllers: { registrations: "users/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root 'home#index'
  root 'tasks#index'

  get '/complete/:id', to: 'tasks#complete', as: 'complete'
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  scope :complete, -> { where(complete: true) }
  scope :incomplete, -> { where(complete: nil) }

  def mark_complete!
    self.update_attribute(:complete, true)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  respond_to :html
  respond_to :js

  def index
    @user = current_user
    @tasks = @user.tasks.all
    respond_with(@tasks)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @user = current_user
    @task = Task.new(task_params)

    if @user.soft_user?
      @task.soft_token = @user.soft_token
    end

    @task.save
    respond_with(@task)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def complete
    @task = Task.find(params[:id])
    @task.mark_complete!
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :complete, :user_id)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task, remote: true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :task_name %>
  </div>

  <div class="field">
    <%= form.label :complete %>
    <%= form.check_box :complete, id: :task_complete %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :task_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<%= div_for task do %>
  <h3><%= task.name %>

    <ul>
      <li><%= link_to "Edit Task", new_task_path, remote: true %></li>
      <li><%= link_to "Mark Complete", complete_path, remote: true %></li>
      <li><%= link_to "Delete Task", task, rmeote: true, method: :delete %></li>
    </ul>
    <% end %>

app/views/tasks/complete.js.erb
$('div#<%= dom_id(@task) %>').fadeOut();
$('.complete-tasks').append('<%= j render partial: "task", locals: {task: @task} %>');
$('div#<%= dom_id(@task) %>').find('h3').css('text-decoration', 'line-through');

app/views/tasks/create.js.erb
$('form').hide();
$('.my-tasks').append('<%= j render partial: "task", locals: {task: @task} %>');
$('.new-task-button').show();

app/views/tasks/destroy.js.erb
$('div#<%= dom_id(@task) %>').fadeOut();

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/edit.js.erb
$('form').hide();
$('div#<%= dom_id(@task) %>').replaceWith('<%= j render("form") %>');

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<div class="my-tasks">
<% @tasks.each do |task| %>
  <%= render task %>
  <% end %>
</div>

<div class="complete-tasks">
  <% @tasks.complete.each do |task| %>
  <h3><%= task.name %></h3>
  <% end %>
</div>

<%= link_to "New Task", new_task_path, remote: true, class: "new-task-button" %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<% if current_user.needs_engagement? %>
<%= link_to 'You Must Register!', new_user_registration_path %>
<% else %>
<%= render 'form', task: @task %>
<% end %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/new.js.erb
$('.new-task-button').after('<%= j render('form') %>');
$('.new-task-button').hide();

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @task.complete %>
</p>

<p>
  <strong>User:</strong>
  <%= @task.user %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/update.js.erb
$('form').hide();
$('div#<%= dom_id(@task) %>').replaceWith('<%= j render partial: "task", locals: {task: @task} %>');